# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- template: debootstrap_architecture_template.yml
  parameters:
    arch: amd64
    qemu_arch: x86_64
- template: debootstrap_architecture_template.yml
  parameters:
    arch: arm64
    qemu_arch: aarch64
- template: debootstrap_architecture_template.yml
  parameters:
    arch: armel
    qemu_arch: arm
- template: debootstrap_architecture_template.yml
  parameters:
    arch: armhf
    qemu_arch: arm
- template: debootstrap_architecture_template.yml
  parameters:
    arch: i386
    qemu_arch: i386
- template: debootstrap_architecture_template.yml
  parameters:
    arch: mips
    qemu_arch: mips
- template: debootstrap_architecture_template.yml
  parameters:
    arch: mips64el
    qemu_arch: mips64el
- template: debootstrap_architecture_template.yml
  parameters:
    arch: mipsel
    qemu_arch: mipsel
#- template: debootstrap_architecture_template.yml   # debootstrap having trouble with ppc64le, will restore later
#  parameters:
#    arch: ppc64el
#    qemu_arch: ppc64le
- template: debootstrap_architecture_template.yml
  parameters:
    arch: s390x
    qemu_arch: s390x
